version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: "6018772623:AAE7gHdXgEnbhNFTHL_3m3D0VSUc56DD4Nw"
      BOT_NAME: "Shoppping_List_Bot"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/shopping_list"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "shopping_list"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
